### ISSUE TITLE
Repository maintenance and updating 

### ISSUE THREAD

**Issue by darothen** [benbovy/PyGChem#5]
**TODO** items for updating repository:

- [ ] Python 3 compat 
- [ ] Remove or depreciate unused/old modules (e.g., globchem)
- [ ] Check the compatibility of the Iris backend with the latest versions of Iris
- [ ] Remove the FortranFormat dependency (actually copied in the repository)
- [ ] Fix the API for reading/writing datasets
- [ ] Xarray backend
- [ ] Unit testing and CI
- [ ] Proper documentation (API reference + some basic examples)
- [ ] Packaging and distribution (pip/conda-forge)

**Comment by tsherwen** [comment]
Hello Daniel, 

I just saw your note on updating and maintaining Ben's PyGChem and thought I would say that I am aware of a compatibly issue with new versions of iris, cartopy, shapely, and geos. Not sure if you've encountered this?

As a temporary fix when I've installed PyGChem on new machines recently I have just reverted the packages using conda to the versions that Ben used for the PyGChem release . 

e.g. 
conda install --channel https://conda.anaconda.org/benbovy iris
conda install --channel https://conda.anaconda.org/benbovy cartopy
conda install --channel https://conda.anaconda.org/benbovy geos
conda install --channel https://conda.anaconda.org/benbovy shapely

There are serval of us in the Evan's group at WACL (York, UK) using Ben's PyGChem with a mixture of GEOS-Chem versions (v9-2 to v11+) with python 2.7. We use anaconda as a package manager on our cluster. 

Cheers, 

Tomas

**Comment by darothen** [comment]
Hi Tomas,

This is good to know. I'm not surprised that updates to iris/cartopy/shapely/geos which have targeted Python 3.5/3.6 may be breaking some backwards compatibility, and I'm sure things in PyGChem need to be updated to take into account those upstream updates.

First and foremost, we should flesh out some regression testing to help track down these issues. That'll help figure out the easiest way to fix them. If your group are actively using PyGChem (especially using Python 2.7), then it would be wonderful if you could help contribute fixes as I slowly begin to update things. 

Truthfully, my top priority is just the xarray backend, which I've actually mostly done offline from this package - I planned on looping it back in once I had finished fleshing out all the functionality I need, then turn my focus on the main PyGChem package. I was hoping to have an informal meeting about Python tools for GEOS-Chem at the IGC8 later this spring, so that all the users out there can brainstorm ways to consolidate the tools used by the community.

**Comment by tsherwen** [comment]
Hello Daniel, 

This all seems good. Its great seeing the tools for using python with GEOS-Chem continue to grow. It would be particularly good to see the functionally of GAMAP/benchmarking routines replicated in Python.

Lets talk closer to IGC8, 

Tomas

**Comment by benbovy** [comment]
@darothen @tsherwen I'm sorry for not being very reactive on this repo. TBH, right now I don't have much time for this. Unfortunately, as I said to Daniel, my new position is not in the field of atmospheric chemistry so pursuing the development of PyGChem is not in my top priorities anymore.

That said, I'm very happy to see this tool still being used and maintained thanks to your interest and your involvement!

Therefore it doesn't really makes sense for me to continue being the only owner/maintainer of this repository. What do you think about moving it to its own organization on GitHub? Who wants to take on the role of main maintainer of PyGChem?

I would be very happy to give you the rights for merging PRs and pushing commits. I think that changes should still mainly go through pull requests, though.

**Comment by darothen** [comment]
@benbovy, I know that @thackray is also interested in continuing to  develop Python-based tools for working with GEOS-Chem output.

I'd be happy to step in as the main maintainer; I've already sort of taken on GEOS-Chem responsibilities for our group at MIT, so this is a natural extension. The question is, what's the best path forward? A few ideas: 

1. Keep everything in this repo, but add maintainers (and keep a GitFlow model based on pull requests)
2. Split off to a separate repo, possibly as its own organization or just managed by a new maintainer
3. Reach out to the GCST and ask to be brought under their organizational umbrella (but move to BitBucket)

Again, I'm happy to chat with all interested parties at the IGC8. I've found a lot of the utility code already included in PyGChem very useful, but I'm not sure how others are using the package. Interfaces to/from the iris/xarray world are by far the most critical thing that the community needs - projects like [PseuoNetCDF](https://github.com/barronh/pseudonetcdf) that go beyond this are very impressive, but duplicate functionality that already exists in the Python world.

**Comment by benbovy** [comment]
> I'd be happy to step in as the main maintainer

Great!

> Interfaces to/from the iris/xarray world are by far the most critical thing that the community needs

I fully agree! A working interface to HEMCO settings would be useful too.

I'd be for moving this repo to its own organization, especially if I'm not the main maintainer anymore. The ownership can then be shared by a few people involved in this. Moreover it would be also an opportunity to bring together the various existing Python tools related to GEOS-Chem and therefore enhance their visibility. BTW I didn't know about PseudoNetCDF, It seems very impressive indeed! 

I'm also open to option 3. I would make sense as PyGChem has currently no other purpose than providing an interface and tools related to GEOS-Chem. We have to make sure that it would be possible for some of us to keep the ownership of the repository without being members of the GCST, though.
